"""元数据 · 它把东西放哪、往哪说话、装什么。

存储、保留策略、渠道、路由、插件体系、Web 界面。

这一组里有四类**改完要重启**的值（``storage.backend``、``plugins.enabled``、
``host`` / ``port``，还有 ``db_path`` 这类连接建立后就不再读的值），它们的
``requires_restart`` 全部标成 ``True``。标记本身不会让热生效失效，
它只是**不撒谎**：设置页顶部那条「有 N 项需重启」的黄条就靠它算出来
（``docs/design/10-settings-center.md`` § 6）。
"""

from __future__ import annotations

from pathlib import Path
from typing import Final

from alterego.kernel.settings import Choice, Setting, SettingKind


__all__ = ["SETTINGS"]


SETTINGS: Final[tuple[Setting, ...]] = (
    # ── 存储 ────────────────────────────────────────────────
    Setting(
        key="storage.backend",
        label="用什么后端存数据",
        description="存储后端插件 id；空值表示跟着随包默认配置走。",
        kind=SettingKind.STR,
        default="",
        group="存储",
        effect="换掉它会让 Agent 从另一个地方读数据——旧库里的对话和记忆留在原地不动，不会自动搬过去。",
        requires_restart=True,
        danger=True,
    ),
    Setting(
        key="storage.db_path",
        label="数据库文件路径",
        description="数据文件放在哪；相对路径会解析到数据目录下面。",
        kind=SettingKind.PATH,
        default=Path("data/alterego.db"),
        group="存储",
        effect="改成一个新路径等于让它从零开始：对话、记忆、动态全部留旧文件里，页面上看起来像换了个人。",
        requires_restart=True,
        danger=True,
    ),
    Setting(
        key="storage.journal_mode",
        label="日志模式",
        description="数据库的写入日志模式，影响崩溃后能不能恢复。",
        kind=SettingKind.ENUM,
        default="WAL",
        group="存储",
        effect="改成 MEMORY 之后读得快一点，但断电时正在写的那一笔会丢，且没有任何补救。",
        choices=(
            Choice("WAL", "WAL（默认）", "读写不互相阻塞，崩溃后能恢复到最后一个完整事务。"),
            Choice(
                "DELETE", "DELETE", "写事务结束就删日志文件；并发读写会互相等待，磁盘上目录会更乱。"
            ),
            Choice("TRUNCATE", "TRUNCATE", "和 DELETE 类似但保留空文件，省一次创建的开销。"),
            Choice("PERSIST", "PERSIST", "保留日志文件不动，只在上面打标记，写放大略小。"),
            Choice("MEMORY", "MEMORY", "日志只留在内存，速度最快，断电丢掉最近写入的那几笔。"),
        ),
        requires_restart=True,
        advanced=True,
    ),
    Setting(
        key="storage.synchronous",
        label="落盘同步级别",
        description="每次写入是否强制刷到磁盘，是速度与安全之间的开关。",
        kind=SettingKind.ENUM,
        default="NORMAL",
        group="存储",
        effect="降到 OFF 之后写入快很多，但操作系统崩溃时最近几条消息会直接消失。",
        choices=(
            Choice("OFF", "OFF", "最快，也最不安全：写入交给操作系统，断电会丢最近的脏页。"),
            Choice("NORMAL", "NORMAL（默认）", "WAL 模式下只在检查点前刷盘，日常速度与安全平衡。"),
            Choice("FULL", "FULL", "每个事务都刷盘，最安全；写入速度明显下降。"),
            Choice("EXTRA", "EXTRA", "比 FULL 更保守，某些平台上会让每个事务多刷一次目录。"),
        ),
        requires_restart=True,
        advanced=True,
    ),
    Setting(
        key="storage.busy_timeout_ms",
        label="写入被占用时等多久",
        description="数据库被别的事务锁住时最多等多少毫秒再报错。",
        kind=SettingKind.INT,
        default=5000,
        group="存储",
        unit="毫秒",
        minimum=1,
        effect="调成 0 之后推演和网页同时写库时立刻报「数据库被锁」，你会看到推演连续失败而不是慢一点。",
        requires_restart=True,
        advanced=True,
    ),
    Setting(
        key="storage.foreign_keys",
        label="启用外键约束",
        description="是否让数据库自己检查「引用的那条记录还在不在」。",
        kind=SettingKind.BOOL,
        default=True,
        group="存储",
        effect="关掉之后删掉一条消息不会再清掉它的附件与向量，库里开始积累指向不存在记录的孤儿行。",
        requires_restart=True,
        advanced=True,
    ),
    Setting(
        key="storage.temp_store",
        label="临时结果放哪",
        description="排序和临时表放在内存还是文件里。",
        kind=SettingKind.ENUM,
        default="MEMORY",
        group="存储",
        effect="改成 FILE 后内存占用降下来，但检索和导出的速度会慢一截。",
        choices=(
            Choice("MEMORY", "内存", "快，代价是复杂查询时多占一些内存。"),
            Choice("FILE", "文件", "省内存，但每次临时排序都要落盘，批量导出明显变慢。"),
            Choice("DEFAULT", "交给数据库决定", "由编译时的默认设置决定，通常就是文件。"),
        ),
        requires_restart=True,
        advanced=True,
    ),
    Setting(
        key="storage.checkpoint_on_start",
        label="启动时做一次检查点",
        description="每次启动时把 WAL 里的内容合并回主库文件。",
        kind=SettingKind.BOOL,
        default=True,
        group="存储",
        effect="关掉之后启动快一点，但 WAL 文件会一直长大，备份时只拷主库文件会漏掉最近的写入。",
        requires_restart=True,
        advanced=True,
    ),
    Setting(
        key="storage.integrity_check_on_start",
        label="启动时检查数据库完整性",
        description="每次启动跑一遍完整性与外键检查。",
        kind=SettingKind.BOOL,
        default=False,
        group="存储",
        effect="打开后每次启动都会全库扫一遍，库大的话启动要等十几秒，但能在你发现异常之前就报出损坏。",
        requires_restart=True,
        advanced=True,
    ),
    Setting(
        key="storage.backup_before_destructive_migration",
        label="破坏性迁移前自动备份",
        description="会删表删列的迁移之前是否先留一份备份。",
        kind=SettingKind.BOOL,
        default=True,
        group="存储",
        effect="关掉它不等于「那就别备份了」，而是「不给退路就别改」：没有备份目录时存储层会直接拒绝执行迁移。",
        requires_restart=True,
        danger=True,
    ),
    # ── 存储（保留策略）────────────────────────────────────
    Setting(
        key="retention.tick_log_keep_days",
        label="推演日志保留多久",
        description="每次 tick 的详细记录保留多少天，超期清理。",
        kind=SettingKind.INT,
        default=90,
        group="存储",
        unit="天",
        minimum=1,
        effect="推演日志占全部存储的八成左右，所以这是唯一一个调低之后磁盘占用真的会明显下降的表。",
    ),
    Setting(
        key="retention.tick_log_detail",
        label="推演日志记多细",
        description="每次都完整记录，还是只留一行摘要。",
        kind=SettingKind.ENUM,
        default="full",
        group="存储",
        effect="改成 summary 后磁盘占用立刻降下来，但事后想复盘「那次它为什么没说话」就查不到中间过程了。",
        choices=(
            Choice("full", "完整", "记下每个阶段的输入输出，可以完整复盘一次推演。"),
            Choice("summary", "只留摘要", "每次 tick 只留结果与耗时，磁盘省得多，过程查不到。"),
        ),
    ),
    Setting(
        key="retention.activity_log_keep_days",
        label="活动记录保留多久",
        description="动态、渠道动作这类活动记录保留多少天。",
        kind=SettingKind.INT,
        default=365,
        group="存储",
        unit="天",
        minimum=1,
        effect="调小后 feed 里翻不到一年前的动态，那些内容对「它在过什么样的日子」是唯一的证据。",
    ),
    Setting(
        key="retention.memory_keep_forever",
        label="长期记忆永久保留",
        description="是否让整理出来的长期记忆不参与清理。",
        kind=SettingKind.BOOL,
        default=True,
        group="存储",
        effect="关掉之后记忆会按上面的天数被清掉，它开始忘记半年前你们聊过什么。",
        danger=True,
    ),
    Setting(
        key="retention.event_log_enabled",
        label="记录事件日志",
        description="是否把事件总线上的每条事件也写进库。",
        kind=SettingKind.BOOL,
        default=False,
        group="存储",
        effect="打开后排查问题能看到完整的事件流，代价是每次推演多写十几行、库涨得快很多。",
        advanced=True,
    ),
    Setting(
        key="retention.auto_vacuum",
        label="自动回收空间",
        description="删掉旧记录之后是否把腾出来的空间还给操作系统。",
        kind=SettingKind.BOOL,
        default=True,
        group="存储",
        effect="关掉后文件只会变大不会变小，删了一年日志磁盘占用也降不下来。",
    ),
    # ── 渠道 ────────────────────────────────────────────────
    Setting(
        key="channels.enabled",
        label="启用哪些渠道",
        description="它能把消息送到哪些地方（文件、网页、企业微信等）。",
        kind=SettingKind.LIST,
        default=("channel.file", "channel.web"),
        group="渠道",
        effect="删掉 channel.web 之后网页打不开它的对话，也收不到它的消息；留空则它说的话只写进文件。",
        requires_restart=True,
    ),
    Setting(
        key="channels.options",
        label="各渠道自己的配置",
        description="每个渠道那段配置，键由那个渠道的插件解释。",
        kind=SettingKind.MAPPING,
        default=None,
        group="渠道",
        effect="配错的键只会影响那一个渠道，其他渠道照常工作。",
        advanced=True,
    ),
    Setting(
        key="routing.primary",
        label="消息默认发到哪",
        description="没特别指定时，它的消息优先送到哪个渠道。",
        kind=SettingKind.STR,
        default="web",
        group="渠道",
        effect="换成一个没启用的渠道，消息会全部落到备选渠道或文件里，你在网页上什么也看不到。",
        requires_restart=True,
    ),
    Setting(
        key="routing.outbound",
        label="同时发到哪几个渠道",
        description="除了主渠道，还要抄送到哪些渠道。",
        kind=SettingKind.LIST,
        default=(),
        group="渠道",
        effect="往里加一个渠道，每条主动消息都会多送一份，手机上会同时收到两份通知。",
        requires_restart=True,
    ),
    Setting(
        key="routing.level",
        label="什么级别的消息才发出去",
        description="筛选往外发的消息：全部、重要、只发紧急。",
        kind=SettingKind.ENUM,
        default="important",
        group="渠道",
        effect="调成 urgent 之后日常闲聊不再推给你，只有它认为非说不可的事才会出现在通知里。",
        choices=(
            Choice("all", "全部", "包括「今天天气不错」这种，通知会明显变多。"),
            Choice(
                "important", "重要及以上（默认）", "日常闲聊留在 feed 里，只有值得打断你的才推送。"
            ),
            Choice("urgent", "只发紧急", "通知里只剩它判断为急事的那几条，安静但容易错过。"),
        ),
    ),
    Setting(
        key="routing.interactive_dedup_hours",
        label="同一条消息多久内不重复推",
        description="同一话题的消息在这个时长内合并，不再重复打扰你。",
        kind=SettingKind.INT,
        default=24,
        group="渠道",
        unit="小时",
        minimum=0,
        effect="调成 0 之后它每想到一次就推一次，同一个念头会在一天里反复出现在通知里。",
    ),
    Setting(
        key="routing.filters",
        label="发送前的过滤规则",
        description="消息出站之前最后一道过滤；这一节的每一行在下面单独列出。",
        kind=SettingKind.MAPPING,
        default=None,
        group="渠道",
        effect="这里的两条规则是硬拦，被拦下的消息不会消失，它会转成内心活动留在日记里。",
    ),
    Setting(
        key="routing.filters.suppress_quiet_hours",
        label="免打扰时段不推送",
        description="落在免打扰时段里的消息是否压下不发。",
        kind=SettingKind.BOOL,
        default=True,
        group="渠道",
        effect="关掉之后半夜也会收到通知，而它在深夜本来就更爱说话。",
    ),
    Setting(
        key="routing.filters.suppress_when_web_active",
        label="你正在看网页时不推送",
        description="网页端开着时是否跳过推送，避免你已经在看还收到通知。",
        kind=SettingKind.BOOL,
        default=False,
        group="渠道",
        effect="打开后你在网页上会收不到通知，因为系统认为你已经看到了——但它只能看到连接在不在，看不到你在不在看。",
    ),
    # ── 插件 ────────────────────────────────────────────────
    Setting(
        key="plugins.enabled",
        label="启用哪些插件",
        description="插件白名单；没列在这里的插件可以被发现但不会加载。",
        kind=SettingKind.LIST,
        default=(),
        group="插件",
        effect="删掉一个 id 之后它的能力当场消失，依赖它的插件会连带加载失败并报「缺少能力」。",
        requires_restart=True,
    ),
    Setting(
        key="plugins.search_paths",
        label="插件搜索路径",
        description="去哪里找插件目录。",
        kind=SettingKind.LIST,
        default=(Path("plugins"),),
        group="插件",
        effect="去掉 plugins 这一项之后随包的三个示例插件全部消失，alterego plugins list 会说一个都没找到。",
        requires_restart=True,
    ),
    Setting(
        key="plugins.auto_reload",
        label="改动插件后自动重载",
        description="开发插件时监视文件改动并自动重新加载。",
        kind=SettingKind.BOOL,
        default=False,
        group="插件",
        effect="打开后你改一行插件代码就会被立刻装回去，代价是后台一直在轮询文件时间，且半成品代码会被执行。",
    ),
    Setting(
        key="plugins.auto_reload_interval_seconds",
        label="多久查一次插件改动",
        description="自动重载的轮询间隔。",
        kind=SettingKind.FLOAT,
        default=1.0,
        group="插件",
        unit="秒",
        minimum=0.2,
        effect="调到 0.2 秒能更快看到改动生效，但空闲时的 CPU 占用会明显到能看见。",
        depends_on="仅在「改动插件后自动重载」打开时生效",
        advanced=True,
    ),
    Setting(
        key="plugins.circuit_breaker_threshold",
        label="插件失败几次就熔断",
        description="一个插件连续失败到这个次数后停止调用它。",
        kind=SettingKind.INT,
        default=5,
        group="插件",
        unit="次",
        minimum=1,
        effect="调低到 1 之后插件偶尔一次的抖动就会让它被停用，而熔断状态只在内存里，重启才恢复。",
    ),
    Setting(
        key="plugins.isolate_failures",
        label="插件失败不影响主流程",
        description="一个插件报错时是否只记下来、让推演继续走。",
        kind=SettingKind.BOOL,
        default=True,
        group="插件",
        effect="关掉之后任何一个插件抛异常都会让整次推演失败，你会看到连续失败计数一路涨到上限。",
        advanced=True,
    ),
    Setting(
        key="plugins.config",
        label="各插件自己的配置",
        description="每个插件那段配置，键由插件自己的 plugin.toml 声明。",
        kind=SettingKind.MAPPING,
        default=None,
        group="插件",
        effect="插件声明的配置项会在这里查到当前值；写错的键不会被内核拦下，而是由插件启动时自己校验。",
        advanced=True,
    ),
    # ── Web 界面 ────────────────────────────────────────────
    Setting(
        key="web.enabled",
        label="启用网页界面",
        description="是否启动本地网页界面。",
        kind=SettingKind.BOOL,
        default=True,
        group="Web 界面",
        effect="关掉之后 alterego serve 不会监听端口，你的唯一入口变成文件渠道的 outbox 目录。",
        requires_restart=True,
    ),
    Setting(
        key="web.host",
        label="监听地址",
        description="网页界面绑定在哪个地址上。",
        kind=SettingKind.STR,
        default="127.0.0.1",
        group="Web 界面",
        effect="改成 0.0.0.0 会让同一个局域网里的设备都能打开它，同时必须把认证打开，否则整台机器的邻居都能读到它的日记。",
        requires_restart=True,
        danger=True,
    ),
    Setting(
        key="web.port",
        label="监听端口",
        description="网页界面在哪个端口上服务。",
        kind=SettingKind.INT,
        default=8765,
        group="Web 界面",
        unit="端口",
        minimum=1,
        maximum=65535,
        effect="换成已经被占用的端口会让服务启动失败并报「地址已被使用」，而它不会自动换一个端口。",
        requires_restart=True,
    ),
    Setting(
        key="web.auth",
        label="认证方式",
        description="打开网页时怎么证明是你。",
        kind=SettingKind.ENUM,
        default="token",
        group="Web 界面",
        effect="选 none 之后任何能访问到这个地址的人都能读它的日记并改它的设置，所以非本机监听时这一项会被拒绝。",
        choices=(
            Choice("token", "访问令牌", "启动时生成一个令牌，用 URL 或请求头带上；适合本机使用。"),
            Choice("password", "口令", "你自己设一个口令，每次浏览器登录；适合长期开着。"),
            Choice("none", "不认证", "任何能连上端口的人都能看和改；只允许在 127.0.0.1 上使用。"),
        ),
        requires_restart=True,
        danger=True,
    ),
    Setting(
        key="web.sse_keepalive_seconds",
        label="实时推送心跳间隔",
        description="多久往浏览器发一次空事件，防止连接被中间设备掐断。",
        kind=SettingKind.INT,
        default=20,
        group="Web 界面",
        unit="秒",
        minimum=1,
        effect="调大到几分钟后，网页会经常显示「已断开」并在重连时补一段历史，消息看起来像延迟了几分钟才出现。",
        advanced=True,
    ),
    Setting(
        key="web.sse_max_connections",
        label="最多几个实时连接",
        description="同时允许多少个浏览器保持实时推送。",
        kind=SettingKind.INT,
        default=20,
        group="Web 界面",
        unit="个",
        minimum=1,
        effect="调小到 1 之后第二个标签页会退回轮询，切页时消息会慢一拍。",
        advanced=True,
    ),
    Setting(
        key="web.page_size",
        label="每页多少条",
        description="聊天记录、feed、日志每页返回多少条。",
        kind=SettingKind.INT,
        default=50,
        group="Web 界面",
        unit="条",
        minimum=1,
        effect="调到 200 之后一次请求拉回四倍的记录，打开历史很长的对话时首屏会明显变慢。",
    ),
)
