"""元数据 · 它怎么活。

常规、推演、打扰预算、人设、学习、设置中心。这一组回答的是
「这个 Agent 过的是什么样的日子」——它的作息、它有多克制、它会不会变。

``effect`` 全部写成可验证的因果陈述（``docs/design/10-settings-center.md`` § 2.2）：
「调高会让它更频繁地找你」是能对上行为的，「影响拟人程度」不是。
``tests/test_settings_metadata.py`` 会检查 ``effect`` 不是空话。

分组顺序就是文件的顺序：通用 → 模拟 → 预算 → 人设 → 学习 → 设置中心。
"""

from __future__ import annotations

from datetime import time
from pathlib import Path
from typing import Final

from alterego.kernel.settings import Choice, Setting, SettingKind


__all__ = ["SETTINGS"]


SETTINGS: Final[tuple[Setting, ...]] = (
    # ── 常规 ────────────────────────────────────────────────
    Setting(
        key="core.data_dir",
        label="数据目录",
        description="它把你的对话、记忆、日记、日志全部放在哪里。",
        kind=SettingKind.PATH,
        default=Path("data"),
        group="常规",
        effect="换一个目录会让它从一个干净的状态重新开始——旧目录里的对话和记忆都不会跟过去。",
        requires_restart=True,
        danger=True,
    ),
    Setting(
        key="core.log_level",
        label="日志级别",
        description="写进日志文件的详细程度。",
        kind=SettingKind.ENUM,
        default="INFO",
        group="常规",
        effect="调到 DEBUG 后每次模型调用都会留下完整请求，排查问题方便，但日志会在几天内涨到几百兆。",
        choices=(
            Choice("DEBUG", "全部细节", "连提示词原文和模型返回都记下来；日志涨得最快。"),
            Choice("INFO", "正常", "记录每次推演、每条消息、每次失败；日常够用。"),
            Choice(
                "WARNING",
                "只记异常",
                "推演照常跑，但日志里只有出问题的地方，事后复盘时看不到过程。",
            ),
            Choice(
                "ERROR", "只记错误", "日志里只剩真正失败的事，连「它今天没说话」的原因都查不到。"
            ),
            Choice(
                "CRITICAL", "只记致命错误", "基本等于关掉日志；只在确认问题不在日志里之后才该用。"
            ),
        ),
    ),
    Setting(
        key="core.log_format",
        label="日志格式",
        description="日志是给人看的彩色文本，还是给机器看的 JSON。",
        kind=SettingKind.ENUM,
        default="console",
        group="常规",
        effect="改成 json 之后终端里就直接读不懂了，但采集工具能逐字段解析；日志处理器是启动时建的，改完要重启。",
        choices=(
            Choice(
                "console", "彩色文本", "终端里人读友好，管道里没有颜色，交给其他程序处理会麻烦。"
            ),
            Choice("json", "JSON 每行一条", "机器好解析，终端里是一行行生数据；适合接采集服务。"),
        ),
        requires_restart=True,
    ),
    Setting(
        key="core.locale",
        label="界面语言",
        description="命令输出与提示词里的语言标记。",
        kind=SettingKind.STR,
        default="zh_CN",
        group="常规",
        effect="改成 en_US 之后命令输出仍是中文，但它写日记和动态时会改用英文。",
    ),
    Setting(
        key="core.timezone",
        label="所在时区",
        description="它按哪个时区判断「现在是几点」——免打扰、生日、日记日期都靠它。",
        kind=SettingKind.STR,
        default="Asia/Shanghai",
        group="常规",
        effect="写错时区会让它的免打扰时段整段错位，你会在大半夜收到它以为的「早上好」。",
        requires_restart=True,
        danger=True,
    ),
    Setting(
        key="core.user_name",
        label="它怎么称呼你",
        description="提示词里用它来叫你，而不是「用户」。",
        kind=SettingKind.STR,
        default="你",
        group="常规",
        effect="改成真名后它说话会带上这个名字；留成「你」它就用第二人称，读起来更像熟人。",
    ),
    Setting(
        key="core.random_seed",
        label="随机种子",
        description="固定它能得到完全可复现的推演；清空则每次启动都不一样。",
        kind=SettingKind.INT,
        default=42,
        group="常规",
        effect="改掉它之后同样的输入会推出不同结果——这是复现事故时最不该动的一个值。",
        requires_restart=True,
        danger=True,
    ),
    # ── 模拟 ────────────────────────────────────────────────
    Setting(
        key="simulation.mode",
        label="推演模式",
        description="它的时间过得多快：跟着真实时间走，还是把它压缩。",
        kind=SettingKind.ENUM,
        default="realtime",
        group="模拟",
        effect="切到 fast 或 turbo 后它一小时能过完一天，日记数量会在你反应过来之前翻好几倍。",
        choices=(
            Choice("realtime", "跟真实时间同步", "十分钟的间隔就是十分钟，它的节奏和你一样。"),
            Choice("fast", "快 5 倍", "它的一天大约五个小时过完，用量随之涨到五倍。"),
            Choice("turbo", "快 20 倍", "几小时烧完当日预算，然后进入降级状态不再主动说话。"),
        ),
        requires_restart=True,
        danger=True,
    ),
    Setting(
        key="simulation.tick_interval_minutes",
        label="多久推演一次",
        description="每隔多少分钟它醒一次，看看这段时间里有没有想法。",
        kind=SettingKind.INT,
        default=5,
        group="模拟",
        unit="分钟",
        minimum=1,
        effect="调小到 1 会让它每分钟醒一次，模型调用量涨到五倍，大多数调用只想出「没什么事」。",
    ),
    Setting(
        key="simulation.speed_multiplier",
        label="模拟时间倍率",
        description="虚拟时钟走得多快，用来快速过完一段日子。",
        kind=SettingKind.FLOAT,
        default=1.0,
        group="模拟",
        unit="倍",
        minimum=0.1,
        maximum=100.0,
        effect="调到 10 之后一次 tick 相当于过去一小时，它的作息和日记日期都会被拉长。",
        advanced=True,
    ),
    Setting(
        key="simulation.npc_tick_interval_minutes",
        label="其他角色多久醒一次",
        description="它身边那些角色（同事、朋友）隔多久做一次自己的事。",
        kind=SettingKind.INT,
        default=30,
        group="模拟",
        unit="分钟",
        minimum=1,
        effect="调小会让那些角色变得勤快，单位时间内你和它的对话里出现别人的次数明显变多。",
    ),
    Setting(
        key="simulation.enable_npc_conversations",
        label="允许角色之间互相说话",
        description="它身边的人能不能自己聊起来，而不只是等着被它提起。",
        kind=SettingKind.BOOL,
        default=True,
        group="模拟",
        effect="关掉之后它的世界里只剩你一个人会说话，动态里也不会再出现和别人的对话。",
    ),
    Setting(
        key="simulation.max_consecutive_tick_failures",
        label="连续失败多少次就停",
        description="推演连续失败到这个次数后停止，避免一直空转烧钱。",
        kind=SettingKind.INT,
        default=5,
        group="模拟",
        unit="次",
        minimum=1,
        effect="调高会让它在模型接口持续报错时多试几次，代价是一直重试一直在花钱。",
        advanced=True,
    ),
    # ── 预算 ────────────────────────────────────────────────
    Setting(
        key="disturb_budget.daily_message_limit",
        label="每天最多主动发几条消息",
        description="每天主动给你发消息的次数上限，不含它回复你的消息。",
        kind=SettingKind.INT,
        default=3,
        group="预算",
        unit="条",
        minimum=0,
        effect="调高会让它更频繁地找你；设为 0 则它只在回复你时说话。",
    ),
    Setting(
        key="disturb_budget.daily_message_limit_urgent",
        label="紧急情况下的上限",
        description="有急事时允许超过日常上限到几条。",
        kind=SettingKind.INT,
        default=5,
        group="预算",
        unit="条",
        minimum=0,
        effect="调低到等于日常上限，等于取消紧急通道——它再急也只能等第二天。",
    ),
    Setting(
        key="disturb_budget.daily_post_limit",
        label="每天最多发几条动态",
        description="动态是发在 feed 里的，不推送到你的聊天窗口。",
        kind=SettingKind.INT,
        default=4,
        group="预算",
        unit="条",
        minimum=1,
        effect="调高后 feed 会明显变热闹，调低到 1 它一天只留下一条痕迹。",
    ),
    Setting(
        key="disturb_budget.quiet_hours",
        label="免打扰时段",
        description="这段时间里它不会主动找你；格式是「开始 结束」，可以跨零点。",
        kind=SettingKind.LIST,
        default=(time(23, 30), time(8, 0)),
        group="预算",
        unit="时:分",
        effect="缩短这段时间会让它在深夜或清早开口；设成两端相同会直接启动失败，因为那等于「全天静默」或「完全不静默」。",
    ),
    Setting(
        key="disturb_budget.min_interval_minutes",
        label="两条消息的最小间隔",
        description="两次主动发消息之间至少隔多久，和每日上限共同生效。",
        kind=SettingKind.INT,
        default=90,
        group="预算",
        unit="分钟",
        minimum=1,
        effect="从 90 改成 5，你会在一小时内收到攒了三天的全部消息——实际频率取每日上限与这条里更严格的那个。",
    ),
    Setting(
        key="disturb_budget.consecutive_no_reply_limit",
        label="你不回几次它就停",
        description="连续几条消息没等到你回复后，它不再主动开口。",
        kind=SettingKind.INT,
        default=3,
        group="预算",
        unit="次",
        minimum=1,
        effect="调到 1 会让它问一次就沉默很久；调高会让它显得有点黏人，但你的沉默不会永久中断它。",
    ),
    Setting(
        key="disturb_budget.pending_topic_ttl_hours",
        label="想说的话能存多久",
        description="被预算拦下的念头会先攒着，超过这个时长就忘掉。",
        kind=SettingKind.INT,
        default=12,
        group="预算",
        unit="小时",
        minimum=1,
        effect="调大会让它把三天前想说的话在今天讲出来，你会看到一段和当下无关的开场白。",
        advanced=True,
    ),
    # ── 人设 ────────────────────────────────────────────────
    Setting(
        key="persona.evolution_enabled",
        label="允许人设自己变化",
        description="它能不能在一段时间后微调自己的性格参数。",
        kind=SettingKind.BOOL,
        default=False,
        group="人设",
        effect="打开后它的性格会慢慢偏离你写的那份人设，每次幅度不大但会累积，且没有「撤销」按钮。",
        danger=True,
    ),
    Setting(
        key="persona.evolution_interval_days",
        label="每隔多久演化一次",
        description="两次人设微调之间至少隔多少天。",
        kind=SettingKind.INT,
        default=30,
        group="人设",
        unit="天",
        minimum=1,
        effect="调到 1 之后它几乎每天都会挪一点性格，一周下来人设就和原来不像了。",
        depends_on="仅在「允许人设自己变化」打开时生效",
    ),
    Setting(
        key="persona.evolution_max_field_delta",
        label="每次最多改多少",
        description="单次演化里一个性格参数的改动上限，1.0 表示可以完全改掉。",
        kind=SettingKind.FLOAT,
        default=0.15,
        group="人设",
        minimum=0.01,
        maximum=1.0,
        effect="调到 1.0 后一次演化就能让某个性格维度从「内向」翻到「外向」，等于换了一个人。",
        depends_on="仅在「允许人设自己变化」打开时生效",
        advanced=True,
    ),
    Setting(
        key="persona.generation_model",
        label="生成人设用哪档模型",
        description="新人设或人设演化时用哪个模型；这里填的是 [llm.routing] 里的档位名。",
        kind=SettingKind.STR,
        default="persona",
        group="人设",
        effect="换成 cheap 之后人设写得省钱了，但生成的性格描述会明显更模板化。",
        advanced=True,
    ),
    # ── 学习 ────────────────────────────────────────────────
    Setting(
        key="study.field",
        label="它深耕哪个方向",
        description="它自己一格一格学起来的那个方向；留空表示按人设的职业去认。",
        kind=SettingKind.STR,
        default="",
        group="学习",
        effect="留空时它会从人设的 occupation 认方向，认不出来就**不学**并告诉你该填什么，而不是随便挑一个方向学。",
    ),
    Setting(
        key="study.rounds",
        label="一次学几格",
        description="一次 study next 连续学几个主题；这里数的是**格**不是轮，一轮等于五格。",
        kind=SettingKind.INT,
        default=1,
        group="学习",
        unit="格",
        minimum=1,
        effect="调高后一次跑好几次模型调用，单次耗时长且花钱多；学到的东西不会更差，只是同一批内容挤在一次里写完。",
    ),
    Setting(
        key="study.recall_limit",
        label="聊天时最多翻出几篇笔记",
        description="聊到专业话题时，从知识库里捞几篇笔记塞进提示词。",
        kind=SettingKind.INT,
        default=3,
        group="学习",
        unit="篇",
        minimum=1,
        effect="调高会让它聊专业话题更像懂行，但笔记会挤掉当前对话本身，回复开始答非所问。",
    ),
    Setting(
        key="study.min_score",
        label="算得上「聊到专业了」的门槛",
        description="召回笔记的分数下限，低于这个分不认为命中了话题。",
        kind=SettingKind.FLOAT,
        default=2.0,
        group="学习",
        unit="分",
        minimum=0.0,
        effect="调到 0 等于每次对话都硬塞专业笔记，它会在你说「今天好累」的时候跟你讲算法。",
    ),
    # ── 设置中心 ────────────────────────────────────────────
    Setting(
        key="settings.show_advanced",
        label="默认展开「高级」分组",
        description="设置页是否一进去就展开直接编辑完整 TOML 的那一块。",
        kind=SettingKind.BOOL,
        default=False,
        group="设置中心",
        effect="打开后设置页每次都会把整个配置文件摊在最前面，日常改一个预算数字要往下滚很久。",
    ),
    Setting(
        key="settings.auto_backup",
        label="改配置前自动备份",
        description="改动配置前是否留一份 alterego.toml.bak。",
        kind=SettingKind.BOOL,
        default=True,
        group="设置中心",
        effect="关掉后你就没有「恢复上一次」这一步可走了——配置写坏的直接后果是启动失败。",
    ),
    Setting(
        key="settings.show_unannotated",
        label="显示没有标注的设置项",
        description="是否显示从类型推测出来的、没人写过说明的设置项。",
        kind=SettingKind.BOOL,
        default=True,
        group="设置中心",
        effect="关掉之后设置页会干净很多，但你在 alterego.toml 里手写的自定义键会连同它们的黄标一起消失，看起来像配置丢了。",
    ),
    Setting(
        key="settings.confirm_diff",
        label="保存前先看差异",
        description="写回配置前是否先给你看一遍「改了哪几行」。",
        kind=SettingKind.BOOL,
        default=True,
        group="设置中心",
        effect="关掉后每次改值都是即时写入，误点一下就直接生效，而记录里只留下一个新的值。",
    ),
)
